import 'dart:convert';
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'package:nuvo/features/races/data/ai_motion_models.dart';
import 'motion_qa/replay_fixture.dart';
import 'motion_qa/replay_runner.dart';
import 'motion_qa/motion_diagnostics.dart';

/// Real-video QA test.
///
/// Loads real video pose fixtures from `test/motion_qa/fixtures/real/`,
/// runs each through MULTIPLE validators (not just the expected one) to
/// build a confusion matrix, and produces a detailed diagnostic report.
///
/// Fixtures are generated by:
///   python3 test/motion_qa/motion_qa_import.py --manifest test/motion_qa/real_video_sources.json
void main() {
  final realDir = Directory('test/motion_qa/fixtures/real');

  if (!realDir.existsSync()) {
    group('Real Video QA', () {
      test('fixtures exist (run motion_qa_import.py)', () {
        // ignore: avoid_print
        print('Real fixtures not found. Run:');
        print('  python3 test/motion_qa/motion_qa_import.py --manifest test/motion_qa/real_video_sources.json');
        expect(true, isTrue, reason: 'Skipped — real fixtures not generated');
      });
    });
    return;
  }

  final fixtureFiles = realDir
      .listSync()
      .where((f) => f.path.endsWith('.json') && !f.path.endsWith('import_log.json'))
      .map((f) => File(f.path))
      .where((f) {
    final json = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    return json['frames'] != null;
  }).toList();

  if (fixtureFiles.isEmpty) {
    group('Real Video QA', () {
      test('at least one fixture exists', () {
        expect(fixtureFiles, isNotEmpty, reason: 'No real fixture JSON files found');
      });
    });
    return;
  }

  // Load all fixtures.
  final fixtures = fixtureFiles.map((f) {
    final json = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    return ReplayFixture.fromJsonString(jsonEncode(json));
  }).toList();

  // Validators to run each fixture through (confusion matrix).
  final allValidators = <String, AiMotionActivity>{
    'jump_squats': AiMotionActivity.jumpSquats,
    'squats': AiMotionActivity.squats,
    'deep_squats': AiMotionActivity.deepSquats,
    'squat_jacks': AiMotionActivity.squatJacks,
    'jumping_jacks': AiMotionActivity.jumpingJacks,
    'lunge_jumps': AiMotionActivity.lungeJumps,
    'lunges': AiMotionActivity.lunges,
  };

  group('Real Video QA — Per-clip diagnostics', () {
    for (final fixture in fixtures) {
      test('${fixture.id} (${fixture.movement})', () {
        final runner = ReplayRunner();

        // Run through the expected validator.
        final expectedResult = runner.run(fixture);

        // ignore: avoid_print
        print('\n=== ${fixture.id} (${fixture.movement}) ===');
        // ignore: avoid_print
        print('  Expected: ${fixture.expected.reps} reps, shouldMatch=${fixture.expected.shouldMatch}');
        // ignore: avoid_print
        print('  Detected: ${expectedResult.detectedReps} reps (expected validator)');
        // ignore: avoid_print
        print('  Frames: ${expectedResult.totalFrames}');
        // ignore: avoid_print
        print('  Missing landmarks: ${expectedResult.missingLandmarkFrames}/${expectedResult.totalFrames}');
        // ignore: avoid_print
        print('  Airborne frames: ${expectedResult.airborneFrames}');
        // ignore: avoid_print
        print('  Tracking frames: ${expectedResult.trackingFrames}');
        // ignore: avoid_print
        print('  Idle after start: ${expectedResult.idleFramesAfterStart}');
        // ignore: avoid_print
        print('  Failure reasons: ${expectedResult.failureReasons}');

        // Run through all other validators for confusion matrix.
        final confusion = <String, int>{};
        for (final entry in allValidators.entries) {
          if (entry.key == fixture.movement) continue;
          final collector = DiagnosticCollector(activity: entry.value, target: 99);
          collector.start();
          for (final frame in fixture.frames) {
            collector.update(frame.toPoseFrame());
          }
          final detected = collector.validator.currentValue;
          if (detected > 0) {
            confusion[entry.key] = detected;
          }
        }

        if (confusion.isNotEmpty) {
          // ignore: avoid_print
          print('  CONFUSION: $confusion');
        } else {
          // ignore: avoid_print
          print('  CONFUSION: none (all other validators returned 0)');
        }

        // Basic sanity: fixture should have been processed without crashing.
        expect(expectedResult.totalFrames, greaterThan(0));
      });
    }
  });

  group('Real Video QA — Confusion matrix', () {
    test('jump squat clips detected by jump squat validator', () {
      final jsqFixtures = fixtures.where((f) => f.movement == 'jump_squats').toList();
      final runner = ReplayRunner();
      var totalReps = 0;
      var detectedReps = 0;
      var clipsDetected = 0;

      for (final fixture in jsqFixtures) {
        final result = runner.run(fixture);
        totalReps += fixture.expected.reps;
        detectedReps += result.detectedReps;
        if (result.detectedReps > 0) clipsDetected++;
      }

      // ignore: avoid_print
      print('\n=== JUMP SQUAT REAL QA ===');
      // ignore: avoid_print
      print('  Clips: ${jsqFixtures.length}');
      // ignore: avoid_print
      print('  Clips with >0 reps: $clipsDetected/${jsqFixtures.length}');
      // ignore: avoid_print
      print('  Total expected reps: $totalReps');
      // ignore: avoid_print
      print('  Total detected reps: $detectedReps');
      if (totalReps > 0) {
        // ignore: avoid_print
        print('  Rep recall: ${(detectedReps / totalReps * 100).toStringAsFixed(1)}%');
      }

      expect(jsqFixtures, isNotEmpty, reason: 'No jump squat real fixtures');
    });

    test('confuser clips do NOT trigger jump squat validator', () {
      final confuserFixtures = fixtures.where((f) =>
          f.movement == 'normal_squats' ||
          f.movement == 'vertical_jumps' ||
          f.movement == 'jumping_jacks'
      ).toList();
      var falseAccepts = 0;

      for (final fixture in confuserFixtures) {
        // Run through jump squat validator specifically.
        final collector = DiagnosticCollector(activity: AiMotionActivity.jumpSquats, target: 99);
        collector.start();
        for (final frame in fixture.frames) {
          collector.update(frame.toPoseFrame());
        }
        final detected = collector.validator.currentValue;
        if (detected > 0) {
          falseAccepts++;
          // ignore: avoid_print
          print('  FALSE ACCEPT: ${fixture.id} (${fixture.movement}) → $detected jump squat reps');
        }
      }

      // ignore: avoid_print
      print('\n=== CONFUSER FALSE ACCEPTS (Jump Squat validator) ===');
      // ignore: avoid_print
      print('  Confuser clips: ${confuserFixtures.length}');
      // ignore: avoid_print
      print('  False accepts: $falseAccepts');
    });

    test('all validators on all real clips — full confusion matrix', () {
      // ignore: avoid_print
      print('\n=== FULL CONFUSION MATRIX (real video) ===');
      // ignore: avoid_print
      print('  ${"Clip ID".padRight(30)} ${"Movement".padRight(16)} ${"JSQ".padRight(6)} ${"SQT".padRight(6)} ${"DSQ".padRight(6)} ${"SJM".padRight(6)} ${"JJ".padRight(6)} ${"LJ".padRight(6)} ${"LUN".padRight(6)}');

      for (final fixture in fixtures) {
        final results = <String, int>{};
        for (final entry in allValidators.entries) {
          final collector = DiagnosticCollector(activity: entry.value, target: 99);
          collector.start();
          for (final frame in fixture.frames) {
            collector.update(frame.toPoseFrame());
          }
          results[entry.key] = collector.validator.currentValue;
        }

        // ignore: avoid_print
        print('  ${fixture.id.padRight(30)} ${fixture.movement.padRight(16)} '
            '${results['jump_squats'].toString().padRight(6)} '
            '${results['squats'].toString().padRight(6)} '
            '${results['deep_squats'].toString().padRight(6)} '
            '${results['squat_jacks'].toString().padRight(6)} '
            '${results['jumping_jacks'].toString().padRight(6)} '
            '${results['lunge_jumps'].toString().padRight(6)} '
            '${results['lunges'].toString().padRight(6)}');
      }
    });
  });

  group('Real Video QA — Per-movement summary', () {
    test('all movements detection summary', () {
      final movements = <String>[
        'jump_squats', 'normal_squats', 'deep_squats',
        'vertical_jumps', 'jumping_jacks', 'squat_jacks',
        'lunge_jumps', 'lunges',
      ];

      // ignore: avoid_print
      print('\n=== PER-MOVEMENT DETECTION SUMMARY ===');
      print('  ${"Movement".padRight(16)} ${"Clips".padRight(8)} ${"ExpReps".padRight(8)} ${"DetReps".padRight(8)} ${"Recall".padRight(8)} ${"Clips>0".padRight(8)}');

      for (final mv in movements) {
        final mvFixtures = fixtures.where((f) => f.movement == mv).toList();
        if (mvFixtures.isEmpty) continue;

        final runner = ReplayRunner();
        var totalExpected = 0;
        var totalDetected = 0;
        var clipsDetected = 0;

        for (final fixture in mvFixtures) {
          final result = runner.run(fixture);
          totalExpected += fixture.expected.reps;
          totalDetected += result.detectedReps;
          if (result.detectedReps > 0) clipsDetected++;
        }

        final recall = totalExpected > 0
            ? '${(totalDetected / totalExpected * 100).toStringAsFixed(1)}%'
            : 'N/A';

        // ignore: avoid_print
        print('  ${mv.padRight(16)} ${mvFixtures.length.toString().padRight(8)} '
            '${totalExpected.toString().padRight(8)} '
            '${totalDetected.toString().padRight(8)} '
            '${recall.padRight(8)} '
            '$clipsDetected/${mvFixtures.length}');
      }
    });
  });

  group('Real Video QA — Fixture validity', () {
    test('all fixtures have valid structure', () {
      for (final fixture in fixtures) {
        expect(fixture.id, isNotEmpty, reason: 'Fixture missing id');
        expect(fixture.movement, isNotEmpty, reason: 'Fixture ${fixture.id} missing movement');
        expect(fixture.frames, isNotEmpty, reason: 'Fixture ${fixture.id} has no frames');
        expect(fixture.expected.reps, greaterThan(0), reason: 'Fixture ${fixture.id} has 0 expected reps');
      }
    });
  });

  group('Real Video QA — Synthetic vs Real comparison', () {
    test('compare acceptance rates', () {
      final runner = ReplayRunner();

      // Real fixtures.
      final realJsq = fixtures.where((f) => f.movement == 'jump_squats').toList();
      var realAccepted = 0;
      var realTotal = 0;
      var realRepsExpected = 0;
      var realRepsDetected = 0;
      for (final fixture in realJsq) {
        final result = runner.run(fixture);
        realTotal++;
        realRepsExpected += fixture.expected.reps;
        realRepsDetected += result.detectedReps;
        if (result.detectedReps == fixture.expected.reps) realAccepted++;
      }

      // Synthetic fixtures (from fixture bank manifest).
      final manifestFile = File('test/motion_qa/fixtures/manifest.json');
      var synthAccepted = 0;
      var synthTotal = 0;
      if (manifestFile.existsSync()) {
        final manifest = jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
        final entries = manifest['fixtures'] as List<dynamic>;
        for (final entry in entries) {
          final m = entry as Map<String, dynamic>;
          if (m['movement'] != 'jump_squats') continue;
          if (!(m['shouldMatch'] as bool)) continue;
          if (m['id'].toString().contains('__')) continue; // skip augmented
          if (m['id'].toString().contains('noisy') || m['id'].toString().contains('minimal')) continue;
          synthTotal++;
          if (m['matched'] as bool) synthAccepted++;
        }
      }

      // ignore: avoid_print
      print('\n=== SYNTHETIC vs REAL COMPARISON (Jump Squat) ===');
      // ignore: avoid_print
      print('  Synthetic clean accept rate: ${synthTotal > 0 ? (synthAccepted / synthTotal * 100).toStringAsFixed(1) : "N/A"}% ($synthAccepted/$synthTotal)');
      // ignore: avoid_print
      print('  Real video accept rate: ${realTotal > 0 ? (realAccepted / realTotal * 100).toStringAsFixed(1) : "N/A"}% ($realAccepted/$realTotal)');
      // ignore: avoid_print
      print('  Real rep recall: ${realRepsExpected > 0 ? (realRepsDetected / realRepsExpected * 100).toStringAsFixed(1) : "N/A"}% ($realRepsDetected/$realRepsExpected)');
    });
  });
}
