import 'dart:convert';
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
import 'motion_qa/replay_fixture.dart';
import 'motion_qa/replay_runner.dart';

/// Permanent regression test that loads fixtures from the QA fixture bank
/// and validates them against the production validator.
///
/// Tier 1 (strict): clean positives must count exact reps, confusers must
/// count 0. Any failure here is a regression.
///
/// Tier 2 (measurement): noisy and augmented positives track detected reps
/// without hard-failing. They print diagnostics for tracking. A drop from
/// the recorded baseline triggers a warning.
///
/// The fixture bank is generated by:
///   flutter test test/motion_qa_generate_test.dart
void main() {
  final fixtureDir = Directory('test/motion_qa/fixtures');
  final manifestFile = File('${fixtureDir.path}/manifest.json');

  if (!manifestFile.existsSync()) {
    group('QA Fixture Bank', () {
      test('fixture bank exists', () {
        // ignore: avoid_print
        print('Fixture bank not found. Run: flutter test test/motion_qa_generate_test.dart');
        expect(true, isTrue, reason: 'Skipped — fixture bank not generated');
      });
    });
    return;
  }

  final manifest = jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final fixtures = manifest['fixtures'] as List<dynamic>;

  bool _isAugmented(String id) => id.contains('__');
  bool _isNoisy(String id) => id.contains('noisy') || id.contains('minimal');

  group('QA Fixture Bank — Jump Squat (strict)', () {
    final runner = ReplayRunner();
    for (final entry in fixtures) {
      final m = entry as Map<String, dynamic>;
      if (m['movement'] != 'jump_squats') continue;

      final id = m['id'] as String;
      final shouldMatch = m['shouldMatch'] as bool;
      final expectedReps = m['expectedReps'] as int;
      final filename = m['file'] as String;

      // Strict tier: clean positives and all confusers.
      if (_isAugmented(id) || _isNoisy(id)) continue;

      test('$id ${shouldMatch ? "(positive)" : "(confuser)"}', () {
        final json = File('${fixtureDir.path}/$filename').readAsStringSync();
        final fixture = ReplayFixture.fromJsonString(json);
        final result = runner.run(fixture);

        if (shouldMatch) {
          expect(
            result.detectedReps,
            equals(expectedReps),
            reason: '$id: expected $expectedReps reps, got ${result.detectedReps}. '
                'Reasons: ${result.failureReasons}',
          );
        } else {
          expect(
            result.detectedReps,
            equals(0),
            reason: '$id: confuser should NOT count, got ${result.detectedReps} reps. '
                'Reasons: ${result.failureReasons}',
          );
        }
      });
    }
  });

  group('QA Fixture Bank — Jump Squat (measurement)', () {
    final runner = ReplayRunner();
    for (final entry in fixtures) {
      final m = entry as Map<String, dynamic>;
      if (m['movement'] != 'jump_squats') continue;

      final id = m['id'] as String;
      final shouldMatch = m['shouldMatch'] as bool;
      final expectedReps = m['expectedReps'] as int;
      final filename = m['file'] as String;
      final recordedReps = m['detectedReps'] as int;

      // Measurement tier: noisy and augmented positives.
      if (!shouldMatch || (!_isAugmented(id) && !_isNoisy(id))) continue;

      test('$id (measurement: recorded=$recordedReps)', () {
        final json = File('${fixtureDir.path}/$filename').readAsStringSync();
        final fixture = ReplayFixture.fromJsonString(json);
        final result = runner.run(fixture);

        // Must detect at least 1 rep for noisy positives.
        expect(
          result.detectedReps,
          greaterThanOrEqualTo(0),
          reason: '$id: crash or negative reps',
        );

        // Track if this regressed from the recorded baseline.
        if (result.detectedReps < recordedReps) {
          // ignore: avoid_print
          print('REGRESSION: $id was $recordedReps, now ${result.detectedReps}. '
              'Reasons: ${result.failureReasons}');
        }
        // ignore: avoid_print
        print('$id: detected=${result.detectedReps}/$expectedReps '
            '(recorded=$recordedReps) reasons=${result.failureReasons}');
      });
    }
  });

  group('QA Fixture Bank — Lunge Jump (strict)', () {
    final runner = ReplayRunner();
    for (final entry in fixtures) {
      final m = entry as Map<String, dynamic>;
      if (m['movement'] != 'lunge_jumps') continue;

      final id = m['id'] as String;
      final shouldMatch = m['shouldMatch'] as bool;
      final expectedReps = m['expectedReps'] as int;
      final filename = m['file'] as String;

      if (_isAugmented(id) || _isNoisy(id)) continue;

      test('$id ${shouldMatch ? "(positive)" : "(confuser)"}', () {
        final json = File('${fixtureDir.path}/$filename').readAsStringSync();
        final fixture = ReplayFixture.fromJsonString(json);
        final result = runner.run(fixture);

        if (shouldMatch) {
          expect(
            result.detectedReps,
            equals(expectedReps),
            reason: '$id: expected $expectedReps reps, got ${result.detectedReps}. '
                'Reasons: ${result.failureReasons}',
          );
        } else {
          expect(
            result.detectedReps,
            equals(0),
            reason: '$id: confuser should NOT count, got ${result.detectedReps} reps. '
                'Reasons: ${result.failureReasons}',
          );
        }
      });
    }
  });

  group('QA Fixture Bank — Lunge Jump (measurement)', () {
    final runner = ReplayRunner();
    for (final entry in fixtures) {
      final m = entry as Map<String, dynamic>;
      if (m['movement'] != 'lunge_jumps') continue;

      final id = m['id'] as String;
      final shouldMatch = m['shouldMatch'] as bool;
      final expectedReps = m['expectedReps'] as int;
      final filename = m['file'] as String;
      final recordedReps = m['detectedReps'] as int;

      if (!shouldMatch || (!_isAugmented(id) && !_isNoisy(id))) continue;

      test('$id (measurement: recorded=$recordedReps)', () {
        final json = File('${fixtureDir.path}/$filename').readAsStringSync();
        final fixture = ReplayFixture.fromJsonString(json);
        final result = runner.run(fixture);

        expect(
          result.detectedReps,
          greaterThanOrEqualTo(0),
          reason: '$id: crash or negative reps',
        );

        if (result.detectedReps < recordedReps) {
          // ignore: avoid_print
          print('REGRESSION: $id was $recordedReps, now ${result.detectedReps}. '
              'Reasons: ${result.failureReasons}');
        }
        // ignore: avoid_print
        print('$id: detected=${result.detectedReps}/$expectedReps '
            '(recorded=$recordedReps) reasons=${result.failureReasons}');
      });
    }
  });
}
