-- Migration 0015: motion control plane registry and immutable release seeds.
-- Additive only. Rollback is a forward fix: disable channel pointers and preserve audit rows.

CREATE TABLE IF NOT EXISTS motion_activities (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, category TEXT NOT NULL, proof_label TEXT NOT NULL, measurement_type TEXT NOT NULL CHECK (measurement_type IN ('repetitions', 'duration', 'distance')), metric TEXT NOT NULL CHECK (metric IN ('reps', 'seconds')), suggested_targets_json TEXT NOT NULL, supported_formats_json TEXT NOT NULL, icon_key TEXT NOT NULL, sort_priority INTEGER NOT NULL DEFAULT 100, featured INTEGER NOT NULL DEFAULT 0, availability TEXT NOT NULL DEFAULT 'supported', metadata_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_motion_activities_availability ON motion_activities(availability, sort_priority);

CREATE TABLE IF NOT EXISTS verifier_releases (id TEXT PRIMARY KEY, activity_id TEXT NOT NULL, semver TEXT NOT NULL, change_class TEXT NOT NULL, engine_type TEXT NOT NULL, spec_schema_version INTEGER NOT NULL, spec_json TEXT NOT NULL, object_key TEXT, checksum TEXT NOT NULL UNIQUE, required_capabilities_json TEXT NOT NULL, minimum_app_build TEXT NOT NULL, compatibility_group TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', release_notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, published_at TEXT, parent_release_id TEXT, FOREIGN KEY(activity_id) REFERENCES motion_activities(id), FOREIGN KEY(parent_release_id) REFERENCES verifier_releases(id));
CREATE INDEX IF NOT EXISTS idx_verifier_releases_activity_status ON verifier_releases(activity_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS activity_channel_releases (activity_id TEXT NOT NULL, channel TEXT NOT NULL CHECK (channel IN ('internal', 'beta', 'stable')), release_id TEXT NOT NULL, rollout_percent INTEGER NOT NULL DEFAULT 0 CHECK (rollout_percent BETWEEN 0 AND 100), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (activity_id, channel), FOREIGN KEY(activity_id) REFERENCES motion_activities(id), FOREIGN KEY(release_id) REFERENCES verifier_releases(id));

CREATE TABLE IF NOT EXISTS race_verifier_assignments (race_id TEXT PRIMARY KEY, activity_id TEXT NOT NULL, release_id TEXT NOT NULL, release_checksum TEXT NOT NULL, assignment_policy TEXT NOT NULL CHECK (assignment_policy IN ('pinned', 'follow_compatible_patch')), compatibility_group TEXT NOT NULL, assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, assignment_reason TEXT NOT NULL, FOREIGN KEY(race_id) REFERENCES races(id), FOREIGN KEY(activity_id) REFERENCES motion_activities(id), FOREIGN KEY(release_id) REFERENCES verifier_releases(id));
CREATE INDEX IF NOT EXISTS idx_race_verifier_assignments_activity ON race_verifier_assignments(activity_id, release_id);

CREATE TABLE IF NOT EXISTS verification_sessions (id TEXT PRIMARY KEY, race_id TEXT NOT NULL, user_id TEXT NOT NULL, activity_id TEXT NOT NULL, release_id TEXT NOT NULL, release_checksum TEXT NOT NULL, spec_schema_version INTEGER NOT NULL, engine_type TEXT NOT NULL, app_version TEXT NOT NULL, app_build TEXT NOT NULL, runtime_capabilities_json TEXT NOT NULL, status TEXT NOT NULL, result_value INTEGER, confidence REAL, failure_reason TEXT, started_at TEXT, completed_at TEXT, motion_session_id TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(race_id) REFERENCES races(id), FOREIGN KEY(activity_id) REFERENCES motion_activities(id), FOREIGN KEY(release_id) REFERENCES verifier_releases(id));
CREATE INDEX IF NOT EXISTS idx_verification_sessions_race ON verification_sessions(race_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_verification_sessions_user ON verification_sessions(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS verifier_evaluation_runs (id TEXT PRIMARY KEY, release_id TEXT NOT NULL, dataset_snapshot_id TEXT NOT NULL, status TEXT NOT NULL, report_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT, FOREIGN KEY(release_id) REFERENCES verifier_releases(id));

ALTER TABLE races ADD COLUMN verifier_release_id TEXT;
ALTER TABLE motion_sessions ADD COLUMN verifier_release_id TEXT;
ALTER TABLE motion_sessions ADD COLUMN verifier_release_checksum TEXT;
ALTER TABLE motion_sessions ADD COLUMN engine_type TEXT;
ALTER TABLE motion_sessions ADD COLUMN spec_schema_version INTEGER;
ALTER TABLE motion_sessions ADD COLUMN assignment_policy TEXT;

INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('push_ups', 'Pushups', 'upper_body', 'pushups', 'repetitions', 'reps', '[6,8,15,25,50,100]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'fitness_center', 1, 1, 'supported', '{"validatorKey":"pushups_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('push_ups-legacy-2026.09.0', 'push_ups', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"push_ups-legacy-2026.09.0","activityId":"push_ups","engineType":"native_v1","nativeValidatorKey":"pushups_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_pushups_v1"]}', '2cd881e880cc7b2e9e7b55aa723438210d4100c9ff9270f82343aeebcb2fb340', '["pose_landmarks_v1","derived_features_v1","native_pushups_v1"]', 'legacy-native-runtime', 'push_ups-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('push_ups', 'stable', 'push_ups-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('jumping_jacks', 'Jumping Jacks', 'cardio', 'jumping jacks', 'repetitions', 'reps', '[15,30,60,100]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'accessibility_new', 3, 1, 'supported', '{"validatorKey":"jumping_jacks_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('jumping_jacks-legacy-2026.09.0', 'jumping_jacks', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"jumping_jacks-legacy-2026.09.0","activityId":"jumping_jacks","engineType":"native_v1","nativeValidatorKey":"jumping_jacks_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_jumping_jacks_v1"]}', 'b19fccd08e29648c15ac608ccdaa34beff3d6cad44c8a900a5fa16f02bb0d0dd', '["pose_landmarks_v1","derived_features_v1","native_jumping_jacks_v1"]', 'legacy-native-runtime', 'jumping_jacks-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('jumping_jacks', 'stable', 'jumping_jacks-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('squats', 'Squats', 'lower_body', 'squats', 'repetitions', 'reps', '[10,25,50,100]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'person_outline', 1, 1, 'supported', '{"validatorKey":"squats_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('squats-legacy-2026.09.0', 'squats', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"squats-legacy-2026.09.0","activityId":"squats","engineType":"native_v1","nativeValidatorKey":"squats_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_squats_v1"]}', '1b931cb25630d013b4b5a6e7a2760919955c7d00fea1b18b6362f30a3878bab5', '["pose_landmarks_v1","derived_features_v1","native_squats_v1"]', 'legacy-native-runtime', 'squats-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('squats', 'stable', 'squats-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('lunges', 'Lunges', 'lower_body', 'lunges', 'repetitions', 'reps', '[10,20,40,60]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_walk', 2, 1, 'supported', '{"validatorKey":"lunges_v1","verificationMethod":"camera_pose","cameraOrientation":"front_or_angle","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('lunges-legacy-2026.09.0', 'lunges', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"lunges-legacy-2026.09.0","activityId":"lunges","engineType":"native_v1","nativeValidatorKey":"lunges_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_lunges_v1"]}', '55116848cd2cd5b29058980ba4cfad410f3dbe1c457a438cb7ca8523c746952c', '["pose_landmarks_v1","derived_features_v1","native_lunges_v1"]', 'legacy-native-runtime', 'lunges-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('lunges', 'stable', 'lunges-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('plank_hold', 'Plank', 'core', 'plank', 'duration', 'seconds', '[20,30,60,120,600]', '["first_to_goal","most_in_window","best_attempt"]', 'straighten', 1, 0, 'supported', '{"validatorKey":"plank_hold_v1","verificationMethod":"camera_pose","cameraOrientation":"side","sessionBehavior":"validated_timer"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('plank_hold-legacy-2026.09.0', 'plank_hold', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"plank_hold-legacy-2026.09.0","activityId":"plank_hold","engineType":"native_v1","nativeValidatorKey":"plank_hold_v1","measurementType":"duration","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_plank_hold_v1"]}', 'ac0de8b393c018cb53f92b5232237b45432e094da9f84d660aecfc266b1fe77d', '["pose_landmarks_v1","derived_features_v1","native_plank_hold_v1"]', 'legacy-native-runtime', 'plank_hold-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('plank_hold', 'stable', 'plank_hold-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('high_knees', 'High Knees', 'cardio', 'high knees', 'repetitions', 'reps', '[10,20,40,60]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_run', 5, 1, 'supported', '{"validatorKey":"high_knees_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('high_knees-legacy-2026.09.0', 'high_knees', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"high_knees-legacy-2026.09.0","activityId":"high_knees","engineType":"native_v1","nativeValidatorKey":"high_knees_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_high_knees_v1"]}', '28e2c369037e2739d20507334ac0232a3837589c85016b4551da0ff990ef2e58', '["pose_landmarks_v1","derived_features_v1","native_high_knees_v1"]', 'legacy-native-runtime', 'high_knees-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('high_knees', 'stable', 'high_knees-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('arm_raises', 'Arm Raises', 'upper_body', 'arm raises', 'repetitions', 'reps', '[10,20,40,60]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'sports_gymnastics', 2, 0, 'supported', '{"validatorKey":"arm_raises_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('arm_raises-legacy-2026.09.0', 'arm_raises', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"arm_raises-legacy-2026.09.0","activityId":"arm_raises","engineType":"native_v1","nativeValidatorKey":"arm_raises_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_arm_raises_v1"]}', '57e6d0a06b7c39e1834c5aa8f989aec38d28ca0f7152ee1c0dfcde0d58560d3f', '["pose_landmarks_v1","derived_features_v1","native_arm_raises_v1"]', 'legacy-native-runtime', 'arm_raises-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('arm_raises', 'stable', 'arm_raises-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('sumo_squats', 'Sumo Squats', 'lower_body', 'sumo squats', 'repetitions', 'reps', '[10,20,40,60]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'accessibility_new', 3, 0, 'supported', '{"validatorKey":"sumo_squats_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('sumo_squats-legacy-2026.09.0', 'sumo_squats', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"sumo_squats-legacy-2026.09.0","activityId":"sumo_squats","engineType":"native_v1","nativeValidatorKey":"sumo_squats_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_sumo_squats_v1"]}', '2c5d159065fdbd3c667426696721d129c223fb4238f1538421b1cd2739b77a5d', '["pose_landmarks_v1","derived_features_v1","native_sumo_squats_v1"]', 'legacy-native-runtime', 'sumo_squats-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('sumo_squats', 'stable', 'sumo_squats-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('side_lunges', 'Side Lunges', 'lower_body', 'side lunges', 'repetitions', 'reps', '[8,16,30,50]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_walk', 4, 0, 'supported', '{"validatorKey":"side_lunges_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('side_lunges-legacy-2026.09.0', 'side_lunges', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"side_lunges-legacy-2026.09.0","activityId":"side_lunges","engineType":"native_v1","nativeValidatorKey":"side_lunges_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_side_lunges_v1"]}', '27b19239d8dff89c486f9de0f513c61d03abad0c590ec7a5d98e30876afeb455', '["pose_landmarks_v1","derived_features_v1","native_side_lunges_v1"]', 'legacy-native-runtime', 'side_lunges-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('side_lunges', 'stable', 'side_lunges-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('deep_squats', 'Deep Squats', 'lower_body', 'deep squats', 'repetitions', 'reps', '[8,15,30,50]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'accessibility_new', 5, 0, 'supported', '{"validatorKey":"deep_squats_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('deep_squats-legacy-2026.09.0', 'deep_squats', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"deep_squats-legacy-2026.09.0","activityId":"deep_squats","engineType":"native_v1","nativeValidatorKey":"deep_squats_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_deep_squats_v1"]}', '8d59b9386e8a44b04bb2f5b15e8bd6de3abcac1fac4213a26b01e42ec13743be', '["pose_landmarks_v1","derived_features_v1","native_deep_squats_v1"]', 'legacy-native-runtime', 'deep_squats-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('deep_squats', 'stable', 'deep_squats-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('squat_jacks', 'Squat Jacks', 'full_body', 'squat jacks', 'repetitions', 'reps', '[8,15,30,50]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'accessibility_new', 6, 0, 'supported', '{"validatorKey":"squat_jacks_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('squat_jacks-legacy-2026.09.0', 'squat_jacks', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"squat_jacks-legacy-2026.09.0","activityId":"squat_jacks","engineType":"native_v1","nativeValidatorKey":"squat_jacks_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_squat_jacks_v1"]}', 'ec04d15d88d0432a4bedd233b345f8678a3e8e223c489e678698529dc7c19b2f', '["pose_landmarks_v1","derived_features_v1","native_squat_jacks_v1"]', 'legacy-native-runtime', 'squat_jacks-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('squat_jacks', 'stable', 'squat_jacks-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('jump_squats', 'Jump Squats', 'full_body', 'jump squats', 'repetitions', 'reps', '[8,15,30,50]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'accessibility_new', 7, 0, 'supported', '{"validatorKey":"jump_squats_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('jump_squats-legacy-2026.09.0', 'jump_squats', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"jump_squats-legacy-2026.09.0","activityId":"jump_squats","engineType":"native_v1","nativeValidatorKey":"jump_squats_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_jump_squats_v1"]}', 'aa7b27ab3895dae63cd48ccc05d5b2c3debf0885ceb30e26894124991fef391b', '["pose_landmarks_v1","derived_features_v1","native_jump_squats_v1"]', 'legacy-native-runtime', 'jump_squats-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('jump_squats', 'stable', 'jump_squats-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('lunge_jumps', 'Lunge Jumps', 'full_body', 'lunge jumps', 'repetitions', 'reps', '[8,15,30,50]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_walk', 8, 0, 'supported', '{"validatorKey":"lunge_jumps_v1","verificationMethod":"camera_pose","cameraOrientation":"front_or_angle","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('lunge_jumps-legacy-2026.09.0', 'lunge_jumps', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"lunge_jumps-legacy-2026.09.0","activityId":"lunge_jumps","engineType":"native_v1","nativeValidatorKey":"lunge_jumps_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_lunge_jumps_v1"]}', '71ec5770d69d93215eb80e0a61e29b4f5d1ce974cba02d7f2cf53ec0f34b03e2', '["pose_landmarks_v1","derived_features_v1","native_lunge_jumps_v1"]', 'legacy-native-runtime', 'lunge_jumps-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('lunge_jumps', 'stable', 'lunge_jumps-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('running_in_place', 'Running in Place', 'cardio', 'running in place', 'repetitions', 'reps', '[50,100,200,400]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_run', 9, 0, 'supported', '{"validatorKey":"running_in_place_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('running_in_place-legacy-2026.09.0', 'running_in_place', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"running_in_place-legacy-2026.09.0","activityId":"running_in_place","engineType":"native_v1","nativeValidatorKey":"running_in_place_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_running_in_place_v1"]}', 'bf0f982accd37f71b093576f0bf71af370bc32fe49807de412731b3df535ea95', '["pose_landmarks_v1","derived_features_v1","native_running_in_place_v1"]', 'legacy-native-runtime', 'running_in_place-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('running_in_place', 'stable', 'running_in_place-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('treadmill_running', 'Treadmill Running', 'cardio', 'treadmill running', 'repetitions', 'reps', '[50,100,200,400]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_run', 10, 0, 'supported', '{"validatorKey":"treadmill_running_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('treadmill_running-legacy-2026.09.0', 'treadmill_running', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"treadmill_running-legacy-2026.09.0","activityId":"treadmill_running","engineType":"native_v1","nativeValidatorKey":"treadmill_running_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_treadmill_running_v1"]}', '83d8e18b604325da2363a8b9d2de25de8f7475e439f8b3a56e501faf37d35249', '["pose_landmarks_v1","derived_features_v1","native_treadmill_running_v1"]', 'legacy-native-runtime', 'treadmill_running-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('treadmill_running', 'stable', 'treadmill_running-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('walking_in_place', 'Walking in Place', 'cardio', 'walking in place', 'repetitions', 'reps', '[40,80,150,300]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_walk', 11, 0, 'supported', '{"validatorKey":"walking_in_place_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('walking_in_place-legacy-2026.09.0', 'walking_in_place', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"walking_in_place-legacy-2026.09.0","activityId":"walking_in_place","engineType":"native_v1","nativeValidatorKey":"walking_in_place_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_walking_in_place_v1"]}', '8a6b7edceefdab7d9032335e0f490f9f4cd935424668cb25788292464d9c7cdd', '["pose_landmarks_v1","derived_features_v1","native_walking_in_place_v1"]', 'legacy-native-runtime', 'walking_in_place-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('walking_in_place', 'stable', 'walking_in_place-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('marching_in_place', 'Marching in Place', 'cardio', 'marching in place', 'repetitions', 'reps', '[40,80,150,300]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_walk', 12, 0, 'supported', '{"validatorKey":"marching_in_place_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('marching_in_place-legacy-2026.09.0', 'marching_in_place', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"marching_in_place-legacy-2026.09.0","activityId":"marching_in_place","engineType":"native_v1","nativeValidatorKey":"marching_in_place_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_marching_in_place_v1"]}', '3a21c88c94c8aeb784ec78d61e07adbdcc8d4861f97884c0952ed2d05113994b', '["pose_landmarks_v1","derived_features_v1","native_marching_in_place_v1"]', 'legacy-native-runtime', 'marching_in_place-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('marching_in_place', 'stable', 'marching_in_place-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('butt_kicks', 'Butt Kicks', 'cardio', 'butt kicks', 'repetitions', 'reps', '[20,40,80,150]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'directions_run', 13, 0, 'supported', '{"validatorKey":"butt_kicks_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('butt_kicks-legacy-2026.09.0', 'butt_kicks', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"butt_kicks-legacy-2026.09.0","activityId":"butt_kicks","engineType":"native_v1","nativeValidatorKey":"butt_kicks_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_butt_kicks_v1"]}', '27f861934fd1e351f8c96958ff62e39689861ca1c7e2bed958d30c274711f1b7', '["pose_landmarks_v1","derived_features_v1","native_butt_kicks_v1"]', 'legacy-native-runtime', 'butt_kicks-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('butt_kicks', 'stable', 'butt_kicks-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('mountain_climbers', 'Mountain Climbers', 'full_body', 'mountain climbers', 'repetitions', 'reps', '[20,40,80,150]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'terrain', 2, 1, 'supported', '{"validatorKey":"mountain_climbers_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('mountain_climbers-legacy-2026.09.0', 'mountain_climbers', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"mountain_climbers-legacy-2026.09.0","activityId":"mountain_climbers","engineType":"native_v1","nativeValidatorKey":"mountain_climbers_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_mountain_climbers_v1"]}', '79bd5262fad1a5db17b7011c1187d64c56277d2fb7be0b5a2e90a00518fcbe41', '["pose_landmarks_v1","derived_features_v1","native_mountain_climbers_v1"]', 'legacy-native-runtime', 'mountain_climbers-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('mountain_climbers', 'stable', 'mountain_climbers-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('burpees', 'Burpees', 'full_body', 'burpees', 'repetitions', 'reps', '[5,10,20,40]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'whatshot', 1, 1, 'supported', '{"validatorKey":"burpees_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('burpees-legacy-2026.09.0', 'burpees', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"burpees-legacy-2026.09.0","activityId":"burpees","engineType":"native_v1","nativeValidatorKey":"burpees_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_burpees_v1"]}', '595b3624bc4666e6caf7f5d4949294508b84a716f98c05e94c6cbdba3543416e', '["pose_landmarks_v1","derived_features_v1","native_burpees_v1"]', 'legacy-native-runtime', 'burpees-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('burpees', 'stable', 'burpees-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('step_ups', 'Step-Ups', 'lower_body', 'step-ups', 'repetitions', 'reps', '[20,40,80,150]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'stairs', 12, 0, 'supported', '{"validatorKey":"step_ups_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('step_ups-legacy-2026.09.0', 'step_ups', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"step_ups-legacy-2026.09.0","activityId":"step_ups","engineType":"native_v1","nativeValidatorKey":"step_ups_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_step_ups_v1"]}', '129387b9ccd447feec62d586f9e717cf5501149a76d255f43fa9f4f9673fe7a0', '["pose_landmarks_v1","derived_features_v1","native_step_ups_v1"]', 'legacy-native-runtime', 'step_ups-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('step_ups', 'stable', 'step_ups-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('calf_raises', 'Calf Raises', 'lower_body', 'calf raises', 'repetitions', 'reps', '[15,25,50,100]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'height', 13, 0, 'supported', '{"validatorKey":"calf_raises_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('calf_raises-legacy-2026.09.0', 'calf_raises', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"calf_raises-legacy-2026.09.0","activityId":"calf_raises","engineType":"native_v1","nativeValidatorKey":"calf_raises_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_calf_raises_v1"]}', '9168a13691ff5161fe5b49271dbaea6a267db2b131881d32e967c9e819a6aa84', '["pose_landmarks_v1","derived_features_v1","native_calf_raises_v1"]', 'legacy-native-runtime', 'calf_raises-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('calf_raises', 'stable', 'calf_raises-legacy-2026.09.0', 100);
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('lateral_steps', 'Lateral Steps', 'lower_body', 'lateral steps', 'repetitions', 'reps', '[20,40,80,150]', '["first_to_goal","most_in_window","best_attempt","timed_attempt"]', 'swap_horiz', 14, 0, 'supported', '{"validatorKey":"lateral_steps_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"count_reps"}');
INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('lateral_steps-legacy-2026.09.0', 'lateral_steps', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"lateral_steps-legacy-2026.09.0","activityId":"lateral_steps","engineType":"native_v1","nativeValidatorKey":"lateral_steps_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","native_lateral_steps_v1"]}', '519a1a25c9283f6e6415f492e003453adf105d9dbed3c84754c31b5ce6faa469', '["pose_landmarks_v1","derived_features_v1","native_lateral_steps_v1"]', 'legacy-native-runtime', 'lateral_steps-native-v1', 'stable', 'Backfilled current local verifier behavior; remote execution remains disabled until generic runtimes are enabled.', CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('lateral_steps', 'stable', 'lateral_steps-legacy-2026.09.0', 100);

INSERT OR IGNORE INTO race_verifier_assignments (race_id, activity_id, release_id, release_checksum, assignment_policy, compatibility_group, assignment_reason) SELECT r.id, r.activity_id, vr.id, vr.checksum, 'follow_compatible_patch', vr.compatibility_group, 'manual_migration' FROM races r JOIN motion_activities ma ON ma.id = r.activity_id JOIN activity_channel_releases ac ON ac.activity_id = ma.id AND ac.channel = 'stable' JOIN verifier_releases vr ON vr.id = ac.release_id WHERE r.activity_id IS NOT NULL AND COALESCE(r.verifier_type, 'preset_pose') <> 'custom_pose_sequence';
UPDATE races SET verifier_release_id = (SELECT a.release_id FROM race_verifier_assignments a WHERE a.race_id = races.id) WHERE verifier_release_id IS NULL AND id IN (SELECT race_id FROM race_verifier_assignments);
