-- Migration 0016: publish the first declarative verifier releases.
-- Additive and reversible by moving the stable channel pointers back to the
-- immutable native releases from 0015. Existing race assignments stay pinned.

INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES
('arm_raises-remote-2026.09.1', 'arm_raises', '2026.09.1', 'minor', 'state_machine_v1', 1, '{"specSchemaVersion":1,"releaseId":"arm_raises-remote-2026.09.1","activityId":"arm_raises","engineType":"state_machine_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","state_machine_v1"],"requiredLandmarks":["leftShoulder","rightShoulder","leftWrist","rightWrist"],"stableFrames":2,"startRules":[{"point":"leftWrist","axis":"y","operator":"gte","threshold":0.58},{"point":"rightWrist","axis":"y","operator":"gte","threshold":0.58}],"activeRules":[{"point":"leftWrist","axis":"y","operator":"lte","threshold":0.42},{"point":"rightWrist","axis":"y","operator":"lte","threshold":0.42}]}', 'be672434a9b5b8dcb1005feaa5361e5ad998bb8f8f41e4db49fcf53fcc4322da', '["pose_landmarks_v1","derived_features_v1","state_machine_v1"]', 'remote-runtime-v1', 'arm_raises-remote-v1', 'stable', 'First declarative release; native release remains the rollback target.', CURRENT_TIMESTAMP),
('squats-remote-2026.09.1', 'squats', '2026.09.1', 'minor', 'state_machine_v1', 1, '{"specSchemaVersion":1,"releaseId":"squats-remote-2026.09.1","activityId":"squats","engineType":"state_machine_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","state_machine_v1"],"requiredLandmarks":["leftHip","rightHip","leftKnee","rightKnee"],"stableFrames":2,"startRules":[{"point":"leftKnee","axis":"y","operator":"lte","threshold":0.68},{"point":"rightKnee","axis":"y","operator":"lte","threshold":0.68}],"activeRules":[{"point":"leftKnee","axis":"y","operator":"gte","threshold":0.78},{"point":"rightKnee","axis":"y","operator":"gte","threshold":0.78}]}', '11ff39c19544b5a2bc92f8faa62fc026d2bb1b2d38f8a830ec9bc5f172ec0219', '["pose_landmarks_v1","derived_features_v1","state_machine_v1"]', 'remote-runtime-v1', 'squats-remote-v1', 'stable', 'First declarative release; native release remains the rollback target.', CURRENT_TIMESTAMP),
('jumping_jacks-remote-2026.09.1', 'jumping_jacks', '2026.09.1', 'minor', 'state_machine_v1', 1, '{"specSchemaVersion":1,"releaseId":"jumping_jacks-remote-2026.09.1","activityId":"jumping_jacks","engineType":"state_machine_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","state_machine_v1"],"requiredLandmarks":["leftShoulder","rightShoulder","leftWrist","rightWrist"],"stableFrames":2,"startRules":[{"point":"leftWrist","axis":"y","operator":"gte","threshold":0.58},{"point":"rightWrist","axis":"y","operator":"gte","threshold":0.58}],"activeRules":[{"point":"leftWrist","axis":"y","operator":"lte","threshold":0.42},{"point":"rightWrist","axis":"y","operator":"lte","threshold":0.42}]}', '843e29162ce715789119f15357cbfb5c52bc3a6bf8c9f29dd58cd0c14189ebbf', '["pose_landmarks_v1","derived_features_v1","state_machine_v1"]', 'remote-runtime-v1', 'jumping_jacks-remote-v1', 'stable', 'First declarative release; native release remains the rollback target.', CURRENT_TIMESTAMP),
('plank_hold-remote-2026.09.1', 'plank_hold', '2026.09.1', 'minor', 'hold_v1', 1, '{"specSchemaVersion":1,"releaseId":"plank_hold-remote-2026.09.1","activityId":"plank_hold","engineType":"hold_v1","measurementType":"duration","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","hold_v1"],"requiredLandmarks":["leftShoulder","rightShoulder","leftHip","rightHip"],"holdRules":[{"point":"leftHip","axis":"y","operator":"gte","threshold":0.3},{"point":"rightHip","axis":"y","operator":"gte","threshold":0.3}],"minHoldMs":250,"maxHoldMs":3600000}', '570eb71027fcc95c5d13bf7fabe76516f98492a173852da7f4e50501dd57447c', '["pose_landmarks_v1","derived_features_v1","hold_v1"]', 'remote-runtime-v1', 'plank_hold-remote-v1', 'stable', 'First declarative hold release; native release remains the rollback target.', CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES
('arm_raises', 'stable', 'arm_raises-remote-2026.09.1', 100),
('squats', 'stable', 'squats-remote-2026.09.1', 100),
('jumping_jacks', 'stable', 'jumping_jacks-remote-2026.09.1', 100),
('plank_hold', 'stable', 'plank_hold-remote-2026.09.1', 100);
