-- Seed the custom-verifier (Teach Nuvo) activity + stable release so those
-- races can mint verification sessions like preset motion races. The release
-- declares the bundled sequence-match engine; the per-race pose spec stays in
-- races.verifier_spec_json — only session provenance is bound here.
INSERT OR IGNORE INTO motion_activities (id, display_name, category, proof_label, measurement_type, metric, suggested_targets_json, supported_formats_json, icon_key, sort_priority, featured, availability, metadata_json) VALUES ('custom_pose_sequence', 'Custom Motion', 'custom', 'custom motion', 'repetitions', 'reps', '[]', '["first_to_goal","most_in_window","best_attempt"]', 'fitness_center', 999, 0, 'hidden', '{"validatorKey":"custom_pose_sequence_v1","verificationMethod":"camera_pose","cameraOrientation":"front","sessionBehavior":"sequence_match"}');

INSERT OR IGNORE INTO verifier_releases (id, activity_id, semver, change_class, engine_type, spec_schema_version, spec_json, checksum, required_capabilities_json, minimum_app_build, compatibility_group, status, release_notes, published_at) VALUES ('custom_pose_sequence-native-2026.09.0', 'custom_pose_sequence', '2026.09.0', 'minor', 'native_v1', 1, '{"specSchemaVersion":1,"releaseId":"custom_pose_sequence-native-2026.09.0","activityId":"custom_pose_sequence","engineType":"native_v1","nativeValidatorKey":"custom_pose_sequence_v1","measurementType":"repetitions","requiredCapabilities":["pose_landmarks_v1","derived_features_v1","sequence_match_v1"]}', '367225f0452d79ca0352702ab875f75c8db95e6392239cc254c59302bd130262', '["pose_landmarks_v1","derived_features_v1","sequence_match_v1"]', 'legacy-native-runtime', 'custom_pose_sequence-native-v1', 'stable', 'Binds Teach Nuvo custom-verifier races to server verification sessions; the per-race pose spec remains the verifier of record.', CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO activity_channel_releases (activity_id, channel, release_id, rollout_percent) VALUES ('custom_pose_sequence', 'stable', 'custom_pose_sequence-native-2026.09.0', 100);
