// W10 — emits the DRAFT publication migration for converted remote releases.
//
// Reads every spec file in ../motion-releases/, recomputes the checksum with
// the exact convention the internal publish route uses
// (`sha256:` + hex SHA-256 of JSON.stringify(spec)), and writes
// ../migrations/DRAFT_converted_remote_releases_batch_A.sql.
//
// The output file is intentionally NOT numbered — no migration tooling will
// ever apply it. Releases are inserted as status 'draft' and no channel
// pointer is touched; promotion happens later via the publish/promote route
// after device validation.
//
// Usage: node scripts/emit_converted_release_sql.mjs [--check]
//   --check  verify the on-disk draft matches a fresh generation (CI gate).

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const releasesDir = new URL('motion-releases/', root);
const draftPath = new URL(
  'migrations/DRAFT_converted_remote_releases_batch_A.sql',
  root,
);

const files = readdirSync(releasesDir)
  .filter((name) => name.endsWith('.json'))
  .sort();

if (files.length === 0) {
  console.error('No release files found in server/worker/motion-releases/.');
  process.exit(1);
}

const rows = [];
for (const file of files) {
  const raw = readFileSync(new URL(file, releasesDir), 'utf8');
  const spec = JSON.parse(raw);
  if (!spec.releaseId || !spec.activityId || !spec.engineType) {
    throw new Error(`${file}: missing releaseId/activityId/engineType`);
  }
  const canonical = JSON.stringify(spec);
  const checksum =
    'sha256:' + createHash('sha256').update(canonical).digest('hex');
  const capabilities = JSON.stringify(spec.requiredCapabilities ?? []);
  const semver = spec.releaseId.match(/(\d+\.\d+\.\d+)$/)?.[1] ?? '2026.10.0';
  rows.push({ spec, canonical, checksum, capabilities, semver });
}

const lines = [];
lines.push(`-- DRAFT — converted remote motion releases (Batch A). NOT APPLIED.`);
lines.push(`--`);
lines.push(`-- Generated by scripts/emit_converted_release_sql.mjs. Do not rename`);
lines.push(`-- to a numbered migration; promotion happens through the internal`);
lines.push(`-- publish/promote flow after on-device validation, not by migrating.`);
lines.push(`--`);
lines.push(`-- Every row is inserted status='draft' with published_at NULL — the`);
lines.push(`-- same state the internal draft route produces. No channel pointers`);
lines.push(`-- (activity_channel_releases) are touched; the native releases stay`);
lines.push(`-- the rollback target on every channel.`);
lines.push(`--`);
lines.push(`-- checksum = 'sha256:' + SHA256(JSON.stringify(spec_json)) — identical`);
lines.push(`-- to the checksum the publish route assigns, so a promoted release is`);
lines.push(`-- byte-identical to the one differential-tested here.`);
lines.push(``);

for (const row of rows) {
  const { spec, canonical, checksum, capabilities, semver } = row;
  const specLiteral = canonical.replaceAll("'", "''");
  const notes =
    `W10 Batch A conversion: declarative scale-invariant ` +
    `${spec.engineType} spec differential-tested against the native ` +
    `validator; awaiting device validation before promotion.`;
  lines.push(`-- ${spec.activityId} (${spec.releaseId})`);
  lines.push(`INSERT OR IGNORE INTO verifier_releases`);
  lines.push(
    `  (id, activity_id, semver, change_class, engine_type, spec_schema_version,`,
  );
  lines.push(
    `   spec_json, checksum, required_capabilities_json, minimum_app_build,`,
  );
  lines.push(
    `   compatibility_group, status, release_notes, parent_release_id,`,
  );
  lines.push(`   published_at, updated_at)`);
  lines.push(`VALUES (`);
  lines.push(`  '${spec.releaseId}',`);
  lines.push(`  '${spec.activityId}',`);
  lines.push(`  '${semver}',`);
  lines.push(`  'minor',`);
  lines.push(`  '${spec.engineType}',`);
  lines.push(`  ${spec.specSchemaVersion},`);
  lines.push(`  '${specLiteral}',`);
  lines.push(`  '${checksum}',`);
  lines.push(`  '${capabilities}',`);
  lines.push(`  'remote-runtime-v1',`);
  lines.push(`  '${spec.activityId}-remote-v1',`);
  lines.push(`  'draft',`);
  lines.push(`  '${notes}',`);
  lines.push(`  '${spec.activityId}-legacy-2026.09.0',`);
  lines.push(`  NULL,`);
  lines.push(`  CURRENT_TIMESTAMP`);
  lines.push(`);`);
  lines.push(``);
}

const output = lines.join('\n');

if (process.argv.includes('--check')) {
  const existing = readFileSync(draftPath, 'utf8');
  if (existing !== output) {
    console.error(
      'DRAFT_converted_remote_releases_batch_A.sql is stale — rerun emit_converted_release_sql.mjs.',
    );
    process.exit(1);
  }
  console.log('Draft SQL matches the on-disk release specs.');
} else {
  writeFileSync(draftPath, output);
  console.log(
    `Wrote ${rows.length} draft releases to migrations/DRAFT_converted_remote_releases_batch_A.sql`,
  );
  for (const row of rows) {
    console.log(`  ${row.spec.releaseId}  ${row.checksum}`);
  }
}
